version: "3.7"
services:
  pyweb3:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 7710:7710
    volumes:
      - ./pyweb-app:/pyweb3
  redis_db:
    image: redis
    ports:
      - 6379:6379
    volumes:
    - ./data:/data